[modules.RIADigiDoc]
imports = ["Foundation", "Swinject"]
testableImports = ["Cuckoo"]
sources = [
    "RIADigiDoc/**/*.swift",
]
output = "RIADigiDocTests/Mocks/Generated/GeneratedMocks+RIADigiDoc.swift"

[modules.RIADigiDoc.options]
glob = true
keepDocumentation = false