[modules.CommonsLib]
imports = ["Foundation", "Swinject", "Cuckoo", "CommonsLib"]
testableImports = ["CommonsLib"]
sources = [
    "Modules/CommonsLib/Sources/**/*.swift",
]
output = "Modules/CommonsLib/Tests/CommonsLibTests/Mocks/Generated/GeneratedMocks+CommonsLib.swift"

[modules.CommonsLib.options]
glob = true
keepDocumentation = false

[modules.UtilsLib]
imports = ["Foundation", "Swinject", "Cuckoo", "UtilsLib", "CommonsLib", "CommonsTestShared"]
testableImports = ["UtilsLib"]
sources = [
    "Modules/UtilsLib/Sources/**/*.swift",
]
output = "Modules/UtilsLib/Tests/UtilsLibTests/Mocks/Generated/GeneratedMocks+UtilsLib.swift"

[modules.UtilsLib.options]
glob = true
keepDocumentation = false

[modules.LibdigidocLib]
imports = ["Foundation", "Swinject", "Cuckoo", "UtilsLib", "CommonsLib", "LibdigidocLibSwift", "CommonsTestShared"]
testableImports = ["LibdigidocLibSwift"]
sources = [
    "Modules/LibdigidocLib/Sources/LibdigidocSwift/**/*.swift",
]
output = "Modules/LibdigidocLib/Tests/LibdigidocTests/Mocks/Generated/GeneratedMocks+LibdigidocLib.swift"

[modules.LibdigidocLib.options]
glob = true
keepDocumentation = false

[modules.RIADigiDoc]
imports = ["Foundation", "Swinject", "Cuckoo", "LibdigidocLibSwift", "CommonsLib", "CommonsTestShared", "UtilsLib"]
sources = [
    "RIADigiDoc/**/*.swift",
]
output = "RIADigiDocTests/Mocks/Generated/GeneratedMocks+RIADigiDoc.swift"

[modules.RIADigiDoc.options]
glob = true
keepDocumentation = false

[modules.FileImportShareExtension]
imports = ["Foundation", "Cuckoo", "UtilsLib", "CommonsLib", "Alamofire"]
testableImports = ["FileImportShareExtension"]
sources = [
    "Extensions/FileImportShareExtension/**/*.swift",
]
output = "Extensions/FileImportShareExtensionTests/Mocks/Generated/GeneratedMocks+FileImportShareExtension.swift"

[modules.FileImportShareExtension.options]
glob = true
keepDocumentation = false